// This file will be auto-generated by Milo when Supabase schema changes are detected
// Initial database types for eListaMo

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          user_id: string
          name: string | null
          email: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name?: string | null
          email?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string | null
          email?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      baon_entries: {
        Row: {
          id: string
          user_id: string
          date: string
          amount: number
          category: string
          description: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date: string
          amount: number
          category: string
          description?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          amount?: number
          category?: string
          description?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      utang_entries: {
        Row: {
          id: string
          user_id: string
          creditor_name: string
          amount: number
          due_date: string | null
          status: 'pending' | 'paid' | 'overdue'
          description: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          creditor_name: string
          amount: number
          due_date?: string | null
          status?: 'pending' | 'paid' | 'overdue'
          description?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          creditor_name?: string
          amount?: number
          due_date?: string | null
          status?: 'pending' | 'paid' | 'overdue'
          description?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

// Type helpers for easier usage
export type Profile = Database['public']['Tables']['profiles']['Row']
export type BaonEntry = Database['public']['Tables']['baon_entries']['Row']
export type UtangEntry = Database['public']['Tables']['utang_entries']['Row']

export type NewProfile = Database['public']['Tables']['profiles']['Insert']
export type NewBaonEntry = Database['public']['Tables']['baon_entries']['Insert']
export type NewUtangEntry = Database['public']['Tables']['utang_entries']['Insert']